# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YTIxY2EwNWJiN2YyNjc1YjNiYzYzZDFkMjgxNGZjMTBiMDZkOWYxYTkyZjdlMTQ3NjE1MTU3M2ViYjg4YWQxOGVlYzc3ODlhNmI5ZDQ4MTk3OTYyMzYyMGE4MmQ4ZTNiZWIwZDFmOWQ3MWM4MzNiNTRkNDE1OGQ1YzlmOGNmNzM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
